### ISSUE TITLE
the theme needs to be updated for new version of tabs in firefox 89

### ISSUE THREAD

**Issue by AwsmLucifer** [nicoth-in/Dark-Space-Theme#3]
![grafik](https://user-images.githubusercontent.com/81403641/120895935-7722fe80-c61f-11eb-9f60-a92ebf794b27.png)
this white is just ugly af :D needs a little bit tweaking i guess, after the new update 

Firefox stable 89 (latest update)

**Comment by nicoth-in** [comment]
This already have been fixed in the latest version, make sure to install it
