### ISSUE TITLE
Change colour of certain text and elements

### ISSUE THREAD

**Issue by Qwerty-Space** [nicoth-in/Dark-Space-Theme#4]
Firefox has changed the colour of URLs in the URL drop-down, and for buttons, text, and checkboxes in settings and bookmarks.

**Comment by nicoth-in** [comment]
@Qwerty-Space Which version of FF are u using?

**Comment by Qwerty-Space** [comment]
89

**Comment by nicoth-in** [comment]
@Qwerty-Space Are you sure you using the latest version of the addon? If so, which colors you think are wrong? Can you provide screenshots please.

**Comment by Qwerty-Space** [comment]
@nicoth-in here's an example, sorry for the late reply
![image](https://user-images.githubusercontent.com/6967592/123331444-37bd4300-d537-11eb-9d96-adb20f138e57.png)

**Comment by nicoth-in** [comment]
@Qwerty-Space I am not sure, what colours you want to change? Text selection?

**Comment by Qwerty-Space** [comment]
The URL on the right of the page title.
It's inconsistent with the purple "accent" colour of the rest of the theme,

**Comment by nicoth-in** [comment]
Okay, I see. The documentation for color codes seems to be outdated. I will look into the Firefox source code and try to find the way to fix it.

**Comment by nicoth-in** [comment]
Unfortunately, it is impossible to change that color in firefox
