### ISSUE TITLE
publishing on thunderbird add-ons portal

### ISSUE THREAD

**Issue by y15un** [nicoth-in/Dark-Space-Theme#7]
hi!

i've done a quick check to see if this can be applied to thunderbird as well, and it is.
![a screen snip showing thunderbird with dark space theme applied.](https://user-images.githubusercontent.com/70875789/184004075-2ea18257-e0d7-41ae-91de-b9dc4e719f0e.png)
sadly, the 'mail toolbar' (containing *get messages* button, etc) has no transparency and i do not know how to fix this.
also, inside the add-ons manager it lacks preview and i don't know why either.
![a screen snip showing thunderbird add-ons manager with dark space theme set as enabled theme, but missing a preview.](https://user-images.githubusercontent.com/70875789/184004015-05f076d7-3d72-4e55-9f53-a3c541591fc2.png)

but anyway. it works as-is, out of the box, without any modification, which is just awesome.
whenever you have a chance please publish the theme on thunderbird add-ons portal, too!

thanks!

**Comment by nicoth-in** [comment]
Sounds interesting, will try to add colors for all UI elements

**Comment by nicoth-in** [comment]
https://addons.thunderbird.net/thunderbird/addon/dark-space-dynamic

**Comment by y15un** [comment]
> https://addons.thunderbird.net/thunderbird/addon/dark-space-dynamic

while this is surely appreciated, it says "can't find what you're looking for."
could you double check the url please? thanks!
