### ISSUE TITLE
weird flicker when firefox in background

### ISSUE THREAD

**Issue by CryRocks** [nicoth-in/Dark-Space-Theme#9]
Hi,

as soon as i have something over firefox with this theme, it flickers ontop of the window. For example, i have a program over firefox like spotify and it flickers weirdly. As soon as i click on firefox again its gone. 

Happens only with this theme, i tested a couple other dynamic themes and didn't saw that issue with them. 
Also Wallpaper Engine makes it really weird.

without Wallpaper Engine: https://i.imgur.com/8ucrgHk.gif
with Wallpaper Engine: https://i.imgur.com/CViJZ08.mp4

since i didn't had that issue with other themes, i assume its a problem with this theme? not really sure tho. I hope its something that can be fixed, would be great since there are no good dynamic themes besides this one.

**Comment by nicoth-in** [comment]
Hi @CryRocks, what OS are you using? I am mostly sure it is a Firefox issue. Also, what is your Firefox version?

**Comment by CryRocks** [comment]
I'm using Windows 11 22h2 (might be a insider preview build) and Firefox is on version 106.0.1 64Bit

Weird thing is, other dynamic themes are working without that flicker issue, but ye maybe it is a firefox issue, Would be sad if it is, since i guess it doesn't get fixed then :D

**Comment by nicoth-in** [comment]
And this flickering only happens on browser top, not all window borders?

**Comment by CryRocks** [comment]
yes only on top and only if its in the background

**Comment by Kewal89** [comment]
Not sure if this is fixed. But Toggling the Theme Extension via Add-ons Manager fixed it for me.

**Comment by CryRocks** [comment]
ye after toggling and updating all addons/themes, it fixed it for me too
